defaults: &defaults
  url: "amqp://localhost:5672"
  exchange_name: "S2.exchange"
  durable: true
  message_timeout: 120

test:
  <<: *defaults
  exchange_name: "S2.exchange.test"
  queue_name: "notifier-test"

development:
  <<: *defaults
  queue_name: "ordertest"
  routing_keys:
  - '*.*.tube.*'
  - '*.*.spincolumn.*'
  - '*.*.tuberack.*'
  - '*.*.order.*'
  - '*.*.transfertubestotubes.*'

production:
  <<: *defaults
  url: "url"
  exchange_name: "psd.s2"
  queue_name: "psd.s2.audit"
